import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const origin = "http://localhost:3000";
const url = new URL(origin);

const getUser = async () => {
  const res = await fetch(`${origin}/api/users?id=1ZzQAxl8ys07zG43HWSR`);
  return res.json();
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  // if (!loggedUserId) return Astro.redirect("/login");

  // const { origin } = Astro.url;

  // useEffect(() => {
  //   fetch(`${origin}/api/users?id=${loggedUserId}`)
  //     .then((res): Promise<User> => res.json())
  //     .then(setUser);

  // }, []);

  return (
    <html lang="es">
      <body className={inter.className}>
        <NavBar user={user} />
        {children}
      </body>
    </html>
  );
}
